from __future__ import annotations

"""Generate Table 6 from the paper.

Table 6 evaluates the *quality of synthetic gene-expression data* generated by
different models using four metrics: KLD, Pairwise Difference (PD),
Log-Cluster, and Cosine Similarity.

This script recreates the table-generation pipeline in a runnable way using
the implementations bundled in this repository:

  - CVAE / CTGAN / TVAE / CopulaGAN (lightweight, in drgat.utils.synth)
  - DRGAT augmentation (latent diffusion on graph-autoencoder latents)

By default, it evaluates the six drugs used throughout the paper and reports
the **average** across drugs (matching the paper's Table 6 description).
"""

import argparse
import json
from pathlib import Path
from typing import Any, Dict, List, Tuple

import numpy as np
import pandas as pd

from drgat.data.datasets import read_data
from drgat.data.pathway_selector import PathwaySelector
#from drgat.eval.metrics import set_seed
from drgat.eval.synth_metrics import compute_all
from drgat.train.train_table1 import (
    encode_latents,
    sample_ddim,
    train_ddim,
    train_graph_autoencoder,
)
from drgat.utils.synth import (
    fit_and_sample_copula,
    fit_and_sample_ctgan,
    fit_and_sample_cvae,
    fit_and_sample_tvae,
)
from drgat.utils.ppi import load_ppi_graph


def _device(name: str):
    import torch

    if name == "auto":
        return torch.device("cuda" if torch.cuda.is_available() else "cpu")
    return torch.device(name)


def _balanced_synth_counts(n_total: int) -> Tuple[int, int]:
    # Keep synthetic counts balanced across classes for a stable comparison.
    n0 = int(round(n_total / 2))
    n1 = int(n_total - n0)
    return n0, n1


def synthesize(
    method: str,
    X: np.ndarray,
    y: np.ndarray,
    seed: int,
    device: str = "auto",
    drgat_graph=None,
    drgat_genes: List[str] | None = None,
) -> np.ndarray:
    """Generate synthetic samples equal in count to real samples.

    Returns only synthetic X (no labels needed for Table 6).
    """

    method = str(method).lower().strip()
    dev = _device(device)
    n_total = int(X.shape[0])
    aug_ratio = 1.0  # Table 6 description: generate samples equal to the real samples.

    if method == "drgat":
        # DRGAT augmentation: graph AE -> latent diffusion -> decode.
        # For a faithful comparison, we require the PPI-induced graph and the
        # selected gene set (passed from the caller).
        if drgat_graph is None or not drgat_genes:
            raise ValueError("DRGAT synthesis for Table 6 requires drgat_graph and drgat_genes.")

        import torch
        import pandas as pd

        df = pd.DataFrame(X, columns=list(drgat_genes))
        ae, edge_index = train_graph_autoencoder(df, drgat_graph, list(drgat_genes), dev, epochs=60)
        Z = encode_latents(ae, edge_index, df, list(drgat_genes))

        ddim = train_ddim(Z.detach(), y.astype(int), dev, epochs=200)
        n0, n1 = _balanced_synth_counts(n_total)
        Z0 = sample_ddim(ddim, n0, Z.size(1), 0, dev)
        Z1 = sample_ddim(ddim, n1, Z.size(1), 1, dev)
        Zs = torch.cat([Z0, Z1], dim=0)
        Xs = ae.decode(Zs).detach().cpu().numpy().astype(np.float32)
        return Xs

    # --- Table 5 baselines (lightweight implementations) ---
    if method == "cvae":
        Xs, _ = fit_and_sample_cvae(X, y, aug_ratio, seed=seed, device=dev)
        return Xs.astype(np.float32)
    if method == "ctgan":
        Xs, _ = fit_and_sample_ctgan(X, y, aug_ratio, seed=seed, device=dev)
        return Xs.astype(np.float32)
    if method == "tvae":
        Xs, _ = fit_and_sample_tvae(X, y, aug_ratio, seed=seed, device=dev)
        return Xs.astype(np.float32)
    if method in {"copulagan", "copulargan", "copula"}:
        Xs, _ = fit_and_sample_copula(X, y, aug_ratio, seed=seed)
        return Xs.astype(np.float32)

    raise ValueError("Unknown method for Table 6: %s" % method)


def run(drugs: List[str], out_dir: Path, seed: int = 42, device: str = "auto") -> Dict[str, Any]:
    out_dir.mkdir(parents=True, exist_ok=True)
    #set_seed(seed)

    methods = [
        ("CVAE", "cvae"),
        ("CTGAN", "ctgan"),
        ("TVAE", "tvae"),
        ("CopularGAN", "copulagan"),
        ("DRGAT", "drgat"),
    ]

    per_method: Dict[str, List[Dict[str, float]]] = {m[0]: [] for m in methods}

    for drug in drugs:
        expr_df, labels_df, ppi_df, pathways_df, target_genes = read_data(drug)

        # Build the PPI graph and select the same gene set DRGAT uses.
        G = load_ppi_graph(ppi_df, confidence_threshold=0.7, take_lcc=True)
        selector = PathwaySelector(G, pathways_df)
        selected_pathways, gene_set, _ = selector.select_for_drug(
            drug=drug,
            target_genes=target_genes,
            k_ratio=0.05,
            n_boot=5,
        )

        genes = [g for g in gene_set if g in expr_df.columns]
        if len(genes) < 5:
            # Fallback to all columns if the pathway-derived gene set is empty.
            genes = list(expr_df.columns)

        X = expr_df[genes].values.astype(np.float32)
        y = labels_df.set_index("sample_id").loc[expr_df.index]["response"].values.astype(int)

        # Induce pathway graph for the selected genes.
        G_pathway = G.subgraph(genes).copy()

        for display, key in methods:
            if key == "drgat":
                Xs = synthesize(key, X, y, seed=seed, device=device, drgat_graph=G_pathway, drgat_genes=genes)
            else:
                Xs = synthesize(key, X, y, seed=seed, device=device)
            met = compute_all(X, Xs, seed=seed)
            per_method[display].append(
                {
                    "drug": drug,
                    "KLD": float(met.kld),
                    "PD": float(met.pd),
                    "Log-Cluster": float(met.log_cluster),
                    "Cosine Sim": float(met.cosine_sim),
                }
            )

    # average across drugs (Table 6 in the paper reports one row per method)
    rows = []
    for display, _ in methods:
        dfm = pd.DataFrame(per_method[display])
        rows.append(
            {
                "Method": display,
                "KLD": float(dfm["KLD"].mean()),
                "PD": float(dfm["PD"].mean()),
                "Log-Cluster": float(dfm["Log-Cluster"].mean()),
                "Cosine Sim": float(dfm["Cosine Sim"].mean()),
            }
        )

    out_df = pd.DataFrame(rows)
    out_df.to_csv(out_dir / "table6_generation_metrics.csv", index=False)
    (out_dir / "table6_generation_metrics.json").write_text(
        json.dumps({"drugs": drugs, "seed": seed, "methods": rows, "per_drug": per_method}, indent=2)
    )
    return {"rows": rows, "csv": str(out_dir / "table6_generation_metrics.csv")}


def main() -> None:
    ap = argparse.ArgumentParser(description="Generate Table 6 (synthetic quality metrics).")
    ap.add_argument("--output-dir", type=str, required=True)
    ap.add_argument("--seed", type=int, default=42)
    ap.add_argument("--device", type=str, default="auto")
    ap.add_argument(
        "--drugs",
        type=str,
        default="Paclitaxel,Cetuximab,Erlotinib,Docetaxel,Cisplatin,Gemcitabine",
        help="Comma-separated list of drugs to average over.",
    )
    args = ap.parse_args()
    drugs = [d.strip() for d in args.drugs.split(",") if d.strip()]
    out = run(drugs, Path(args.output_dir), seed=args.seed, device=args.device)
    print(json.dumps(out, indent=2))


if __name__ == "__main__":
    main()
